### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by MohamadSH** [AltThree/Emoji#12]
Hi ,
First of all let me thank you for this great package. The problem is that there is no document on how to use it. I actually have added this to my project but really don't know where to go with it. I was wondering if you could provide any examples or whatever which will be helpful. 
Thanks a lot

**Comment by GrahamCampbell** [comment]
If you're using laravel, just add the service provider, and you're done.

**Comment by GrahamCampbell** [comment]
See https://github.com/GrahamCampbell/Laravel-Markdown for how to use the markdown system.

**Comment by MohamadSH** [comment]
Thank you for your response.
I think I have misunderstood the usage of this package. I was looking for something that would emojify a given text so I can send it via telegram API. I mean for example :
given text :" I :h e a r t: you  " => processing on the sentence and then sending it => what you see in telegram client: "I :heart: you"

but what this package does is transferring :h e a r t: to the HTML image tag so you can see the heart in the browser . Am I right? You can't imagine how much I love to hear that I have not got this right and I can use it to do what I want with this package!!!

**Comment by GrahamCampbell** [comment]
I'm not 100% what you mean. Our behaviour is defined by our tests though. Maybe they'll help you understand. https://github.com/AltThree/Emoji/blob/master/tests/EmojiParserTest.php

**Comment by MohamadSH** [comment]
I'm sorry for confusing you. I am working on a laravel project that is supposed to send message via a telegram bot. The major problem in implementing  a project like this , is sending messages with emoji. I also have found this package but it is not really helpful:  https://github.com/iamcal/php-emoji.
I was hopping perhaps your package offers a better easier way for what I need to do but I suppose that is not true.
Anyway , thank you for your patience!
