### ISSUE TITLE
EmojiParser unresolvable dependency

### ISSUE THREAD

**Issue by jbrooksuk** [AltThree/Emoji#14]
When using `EmojiExtension` with @GrahamCampbell's Markdown package, the following occurs:

> Unresolvable dependency resolving [Parameter #0 [ <required> array $map ]] in class AltThree\Emoji\EmojiParser

**Comment by GrahamCampbell** [comment]
The test suite in this package shows that it does work.

**Comment by GrahamCampbell** [comment]
Just checked cachet and it's due to you not upgrading it properly, not a bug in this package, lol.

**Comment by jbrooksuk** [comment]
Lol.

**Comment by cjmaxik** [comment]
It doesn't worked
Laravel 5.3.24

`Unresolvable dependency resolving [Parameter #0 [ <required> array $map ]] in class AltThree\Emoji\EmojiParser (View: xxx)`

**Comment by GrahamCampbell** [comment]
Will only happen if you forget to register the service provider.
