### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by HDVinnie** [AltThree/Emoji#15]
Upon installing this does this mean I can just type :s m i l i e: in my textarea on my app for comments and it will automatically show as 😄 when posted? Im new to laravel so please excuse my noobness.

```
<!-- Add comment -->
<div class="col-md-12">
  {!! Form::open(array('route' => array('comment_torrent', 'slug' => $torrent->slug, 'id' => $torrent->id))) !!}
  <div class="form-group">
    <label for="content">Your comment:</label>
    <textarea name="content" cols="30" rows="5" class="form-control"></textarea>
  </div>
  <button type="submit" class="btn btn-danger">{!! trans('traduction.save') !!}</button><label class="checkbox-inline"><input type="checkbox" name="confirmation"><strong>Anonymous Comment</strong></label>
  {!! Form::close() !!}
</div>
<!-- /Add comment -->
```

**Comment by jbrooksuk** [comment]
Not exactly.

When using @GrahamCampbell's [Laravel Markdown](http://github.com/GrahamCampbell/Laravel-Markdown) package you can install this package alongside it and it'll convert `:smile:` to 😄.

For an example on how to use it see [Cachet](https://github.com/CachetHQ/Cachet).
