### ISSUE TITLE
hit rate limit exceeded even add github oauth token in config

### ISSUE THREAD

**Issue by pilishen** [AltThree/Emoji#16]
correct me if i'm wrong~

when using with laravel-markdown, got the github rate limit exceeded problem, so i add GITHUB_TOKEN in env with the value of my personal access token, after config:cache command, bad luck however.

after digging around, i changed [EmojiServiceProvider](https://github.com/AltThree/Emoji/blob/master/src/EmojiServiceProvider.php), line 79:

originally:
```
$headers['OAUTH-TOKEN'] = $token;
```

into:
```
$headers['Authorization'] = 'token '.$token;
```

according to this url : https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/#3-use-the-access-token-to-access-the-api

now it works.

 can any guys help to  confirm this ?

**Comment by GrahamCampbell** [comment]
Thanks for the report. 👍 

Will be fixed in the next release, which will be tagged within the next 30 mins. 🚀

**Comment by pilishen** [comment]
excellent! thanks~
