### ISSUE TITLE
Type error: json_decode() expects parameter 1 to be a string, object given

### ISSUE THREAD

**Issue by ghost** [AltThree/Emoji#17]
As soon as I add the EmojiExtension Class to the extensions array from Laravel Markdown I get an Type error.

```php
  /*
    |--------------------------------------------------------------------------
    | CommonMark Extensions
    |--------------------------------------------------------------------------
    |
    | This option specifies what extensions will be automatically enabled.
    | Simply provide your extension class names here.
    |
    | Default: []
    |
    */

    'extensions' => [
        AltThree\Emoji\EmojiExtension::class,
    ],
```

> Type error: json_decode() expects parameter 1 to be a string, object given
> in **EmojiServiceProvider.php** (line 84)

I am working with Laravel 5.4

**Comment by GrahamCampbell** [comment]
Thanks for the report. This regression was caused by our strict types addition.

**Comment by GrahamCampbell** [comment]
Will be fixed in the next release, which will be tagged very soon. 🚢
