### ISSUE TITLE
Add classname to img tag

### ISSUE THREAD

**Issue by jbrooksuk** [AltThree/Emoji#2]
Emojis will render at 100% size and in some cases (like ours) we're unable to style all images to fit. Ideally we need a classname of `emoji` on the image tag.

**Comment by jbrooksuk** [comment]
I did try this myself, even writing a custom `Image` class, but there was some error about inline rendering or something. I'll take another gander later.

**Comment by ConnorVG** [comment]
It'd be great if it was a class of something along the lines of: `emoji emoji--poop` for :poop: etc

**Comment by jbrooksuk** [comment]
Good idea @ConnorVG, this would be useful!

**Comment by GrahamCampbell** [comment]
We can't include the emoji name in the class name because some emojis contain characters that are invalid for class names.

**Comment by jbrooksuk** [comment]
Any examples? I can't think of any on the top of my head.

**Comment by GrahamCampbell** [comment]
`:+1:`?

**Comment by jbrooksuk** [comment]
Lol, that's my favourite emoji too.

We could strip any non alphanum chars and then prefix with `emoji-`?

**Comment by GrahamCampbell** [comment]
That wouldn't work.

**Comment by GrahamCampbell** [comment]
Then `:+1:` and `:-1:` would have the same class.

**Comment by GrahamCampbell** [comment]
And `emoji--1` looks silly.

**Comment by GrahamCampbell** [comment]
I see no need to include the emoji name in the class name tbh.

**Comment by GrahamCampbell** [comment]
Just choose one class name and use it everywhere and be done with it imo.

**Comment by jbrooksuk** [comment]
`emoji` will do.

**Comment by GrahamCampbell** [comment]
CommonMark doesn't seem to support setting the class anyway.

**Comment by jbrooksuk** [comment]
Yeah, it's crap. I opened an issue for it.

**Comment by GrahamCampbell** [comment]
> I opened an issue for it.

Where?

**Comment by GrahamCampbell** [comment]
Can't see it on https://github.com/thephpleague/commonmark/issues?

**Comment by jbrooksuk** [comment]
https://github.com/thephpleague/commonmark/issues/145

**Comment by GrahamCampbell** [comment]
That issue doesn't scribe what we want though.

**Comment by GrahamCampbell** [comment]
We don't want a way to set the class from the markdown, we want a way to set the class from the code itself.

**Comment by GrahamCampbell** [comment]
So the link to that extension is totally useless to us.

**Comment by jbrooksuk** [comment]
Hmmm, I figured it was an inline element, since we're currently using `Image`.

**Comment by GrahamCampbell** [comment]
It's more that Colin didn't understand the question, and thinks you wanted a way to set the class from the markdown document.

**Comment by jbrooksuk** [comment]
Yeah, I didn't explain very well. I'll re-word.

**Comment by ConnorVG** [comment]
How about just have an emoji class and a `data-emoji="+1"` instead?

**Comment by GrahamCampbell** [comment]
What's the point in that, when you could just read the alt text?

**Comment by ConnorVG** [comment]
[data-] is for this kind of stuff, it suits the purpose more than the human readable purpose of an alt tag.

**Comment by GrahamCampbell** [comment]
We can't set the data attribute anyway.

**Comment by GrahamCampbell** [comment]
In the same way we can't set the class.

**Comment by ConnorVG** [comment]
The reasoning to wanting this feature is for stuff such as reversing the content (for instance, in a content editable field).

If it's not currently possible then I understand.

**Comment by jbrooksuk** [comment]
Well, if the proposed changes to Commonmark make it through, data tags will be a thing.
