### ISSUE TITLE
why revert the support for laravel 5.6?

### ISSUE THREAD

**Issue by pilishen** [AltThree/Emoji#23]
try using in laravel 5.6, it complains the version conflict.
found that there was a revertion which dropped the support for 5.6
wonder reason
thanks in advance

**Comment by GrahamCampbell** [comment]
Because we are not ready yet. There are some more changes to be made. Support will be coming this week though. Don't worry. :)

**Comment by pilishen** [comment]
got it, thanks~

**Comment by GrahamCampbell** [comment]
v6.0 released with laravel 5.6 support
